version: "3"
services:
  builder:
    image: debian:bullseye-slim
    working_dir: /app
    volumes:
      - ../../:/app
    environment:
      - DEBIAN_FRONTEND=noninteractive
    command: >
      sh -c "
        apt-get update &&
        apt-get install -y --no-install-recommends
          build-essential
          fakeroot
          devscripts
          debhelper
          nodejs
          npm
        "
